---
ansible_port: 5542
ansible_user: senzi
timezone: "Europe/Moscow"
sys_packages:
  - btop
  - curl
  - wget
  - git
  - ncdu
  - ufw
  - fastfetch
admin_user: "senzi"
# admin_keys в отдельном ansible/secrets.yml