---
target_ssh_port: 5542
timezone: "Europe/Moscow"
admin_user: "senzi"
sys_packages:
  - btop
  - curl
  - wget
  - git
  - ncdu
  - ufw
  - fastfetch
  - vim
# admin_keys в отдельном ansible/secrets.yml