---
ssh_port: 5542
timezone: "Europe/Moscow"
sys_packages:
  - btop
  - curl
  - wget
  - git
  - ncdu
  - ufw
  - fastfetch
bootstrap_user: "root"
admin_user: "senzi"
# admin_keys в отдельном ansible/secrets.yml